-- ============================================================
-- NOMARCHY: database check
-- Paste this whole file into the Supabase SQL Editor and press Run. It only
-- reads - it changes nothing. You'll get either one "All good" line, or a
-- list of what's missing. If anything is missing, paste and run the full
-- schema.sql (it's always safe to re-run), then run this check again.
--
-- Generated from schema.sql by `npm run db:check` - don't edit by hand.
-- ============================================================
with checks(item, ok) as (
  values
    ('Latest version of schema.sql has been run (790bb0367d63)', exists (select 1 from schema_migrations where name = 'schema-version:790bb0367d63')),
    ('Table: schema_migrations', to_regclass('public.schema_migrations') is not null),
    ('Table: profiles', to_regclass('public.profiles') is not null),
    ('Table: cuisines', to_regclass('public.cuisines') is not null),
    ('Table: thrones', to_regclass('public.thrones') is not null),
    ('Table: fallen', to_regclass('public.fallen') is not null),
    ('Table: next_in_line', to_regclass('public.next_in_line') is not null),
    ('Table: endorsements', to_regclass('public.endorsements') is not null),
    ('Table: follows', to_regclass('public.follows') is not null),
    ('Table: blocks', to_regclass('public.blocks') is not null),
    ('Table: rank_promotions', to_regclass('public.rank_promotions') is not null),
    ('Table: dismissed_notifications', to_regclass('public.dismissed_notifications') is not null),
    ('Table: ai_calls', to_regclass('public.ai_calls') is not null),
    ('Table: place_lookup_cache', to_regclass('public.place_lookup_cache') is not null),
    ('Table: restaurants', to_regclass('public.restaurants') is not null),
    ('Table: feedback', to_regclass('public.feedback') is not null),
    ('Table: conquests', to_regclass('public.conquests') is not null),
    ('Table: signup_sources', to_regclass('public.signup_sources') is not null),
    ('Table: invites', to_regclass('public.invites') is not null),
    ('Table: google_api_calls', to_regclass('public.google_api_calls') is not null),
    ('Table: place_refresh_issues', to_regclass('public.place_refresh_issues') is not null),
    ('Table: closed_places', to_regclass('public.closed_places') is not null),
    ('Table: place_pages', to_regclass('public.place_pages') is not null),
    ('Table: app_errors', to_regclass('public.app_errors') is not null),
    ('Table: content_removals', to_regclass('public.content_removals') is not null),
    ('View: standings', to_regclass('public.standings') is not null),
    ('Column: profiles.is_owner', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'profiles' and column_name = 'is_owner')),
    ('Column: profiles.is_public', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'profiles' and column_name = 'is_public')),
    ('Column: profiles.avatar_url', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'profiles' and column_name = 'avatar_url')),
    ('Column: profiles.onboarded', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'profiles' and column_name = 'onboarded')),
    ('Column: profiles.discoverable', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'profiles' and column_name = 'discoverable')),
    ('Column: profiles.unsubscribe_token', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'profiles' and column_name = 'unsubscribe_token')),
    ('Column: profiles.reminders_opt_out', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'profiles' and column_name = 'reminders_opt_out')),
    ('Column: profiles.notifications_seen_at', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'profiles' and column_name = 'notifications_seen_at')),
    ('Column: profiles.last_rank_min', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'profiles' and column_name = 'last_rank_min')),
    ('Column: profiles.notify_follows', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'profiles' and column_name = 'notify_follows')),
    ('Column: profiles.notify_crowns', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'profiles' and column_name = 'notify_crowns')),
    ('Column: profiles.notify_reviews', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'profiles' and column_name = 'notify_reviews')),
    ('Column: profiles.notify_endorsements', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'profiles' and column_name = 'notify_endorsements')),
    ('Column: profiles.hidden_cuisine_ids', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'profiles' and column_name = 'hidden_cuisine_ids')),
    ('Column: next_in_line.visited_at', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'next_in_line' and column_name = 'visited_at')),
    ('Column: next_in_line.lat', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'next_in_line' and column_name = 'lat')),
    ('Column: next_in_line.lng', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'next_in_line' and column_name = 'lng')),
    ('Column: next_in_line.verdict', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'next_in_line' and column_name = 'verdict')),
    ('Column: next_in_line.city', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'next_in_line' and column_name = 'city')),
    ('Column: thrones.city', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'thrones' and column_name = 'city')),
    ('Column: thrones.photos', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'thrones' and column_name = 'photos')),
    ('Column: next_in_line.photos', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'next_in_line' and column_name = 'photos')),
    ('Column: thrones.coords_refreshed_at', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'thrones' and column_name = 'coords_refreshed_at')),
    ('Column: next_in_line.coords_refreshed_at', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'next_in_line' and column_name = 'coords_refreshed_at')),
    ('Column: profiles.tour_seen_at', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'profiles' and column_name = 'tour_seen_at')),
    ('Column: cuisines.emoji', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'cuisines' and column_name = 'emoji')),
    ('Column: profiles.a11y_prefs', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'profiles' and column_name = 'a11y_prefs')),
    ('Old column removed: profiles.digest_opt_out', not exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'profiles' and column_name = 'digest_opt_out')),
    ('Function: handle_new_user', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'handle_new_user')),
    ('Function: protect_is_owner', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'protect_is_owner')),
    ('Function: archive_dethroned', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'archive_dethroned')),
    ('Function: match_restaurant', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'match_restaurant')),
    ('Function: search_restaurants_fuzzy', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'search_restaurants_fuzzy')),
    ('Function: next_in_line_recent_count', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'next_in_line_recent_count')),
    ('Function: review_photos_recent_count', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'review_photos_recent_count')),
    ('Function: restaurant_visit_count', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'restaurant_visit_count')),
    ('Function: restaurant_wanting_count', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'restaurant_wanting_count')),
    ('Function: record_signup_source', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'record_signup_source')),
    ('Function: claim_invite', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'claim_invite')),
    ('Function: google_usage_summary', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'google_usage_summary')),
    ('Function: stamp_coords_refreshed', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'stamp_coords_refreshed')),
    ('Function: protect_cuisine_fields', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'protect_cuisine_fields')),
    ('Function: place_street_key', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'place_street_key')),
    ('Function: place_text_key', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'place_text_key')),
    ('Function: best_in_land', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'best_in_land')),
    ('Function: slug_part', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'slug_part')),
    ('Function: ensure_place_page', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'ensure_place_page')),
    ('Function: place_page_from_row', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'place_page_from_row')),
    ('Function: place_page', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'place_page')),
    ('Function: place_pages_for_sitemap', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'place_pages_for_sitemap')),
    ('Function: report_error', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'report_error')),
    ('Function: my_profile', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'my_profile')),
    ('Function: admin_profiles', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'admin_profiles')),
    ('Function: check_username', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'check_username')),
    ('Function: feedback_recent_count', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'feedback_recent_count')),
    ('Trigger: on_auth_user_created', exists (select 1 from pg_trigger where tgname = 'on_auth_user_created' and not tgisinternal)),
    ('Trigger: protect_is_owner_trigger', exists (select 1 from pg_trigger where tgname = 'protect_is_owner_trigger' and not tgisinternal)),
    ('Trigger: on_throne_replaced', exists (select 1 from pg_trigger where tgname = 'on_throne_replaced' and not tgisinternal)),
    ('Trigger: stamp_coords_thrones', exists (select 1 from pg_trigger where tgname = 'stamp_coords_thrones' and not tgisinternal)),
    ('Trigger: stamp_coords_nil', exists (select 1 from pg_trigger where tgname = 'stamp_coords_nil' and not tgisinternal)),
    ('Trigger: protect_cuisine_fields_trigger', exists (select 1 from pg_trigger where tgname = 'protect_cuisine_fields_trigger' and not tgisinternal)),
    ('Trigger: thrones_place_page', exists (select 1 from pg_trigger where tgname = 'thrones_place_page' and not tgisinternal)),
    ('Trigger: next_in_line_place_page', exists (select 1 from pg_trigger where tgname = 'next_in_line_place_page' and not tgisinternal)),
    ('Trigger: check_username_trigger', exists (select 1 from pg_trigger where tgname = 'check_username_trigger' and not tgisinternal)),
    ('Index: profiles_unsubscribe_token_idx', to_regclass('public.profiles_unsubscribe_token_idx') is not null),
    ('Index: cuisines_unique_name_per_owner', to_regclass('public.cuisines_unique_name_per_owner') is not null),
    ('Index: thrones_user_idx', to_regclass('public.thrones_user_idx') is not null),
    ('Index: fallen_user_idx', to_regclass('public.fallen_user_idx') is not null),
    ('Index: nil_user_idx', to_regclass('public.nil_user_idx') is not null),
    ('Index: rank_promotions_user_idx', to_regclass('public.rank_promotions_user_idx') is not null),
    ('Index: ai_calls_user_id_called_at_idx', to_regclass('public.ai_calls_user_id_called_at_idx') is not null),
    ('Index: restaurants_name_trgm_idx', to_regclass('public.restaurants_name_trgm_idx') is not null),
    ('Index: restaurants_city_idx', to_regclass('public.restaurants_city_idx') is not null),
    ('Index: invites_inviter_idx', to_regclass('public.invites_inviter_idx') is not null),
    ('Index: google_api_calls_kind_created_idx', to_regclass('public.google_api_calls_kind_created_idx') is not null),
    ('Index: follows_followee_idx', to_regclass('public.follows_followee_idx') is not null),
    ('Index: endorsements_throne_idx', to_regclass('public.endorsements_throne_idx') is not null),
    ('Index: blocks_blocked_idx', to_regclass('public.blocks_blocked_idx') is not null),
    ('Index: thrones_google_place_idx', to_regclass('public.thrones_google_place_idx') is not null),
    ('Index: nil_google_place_idx', to_regclass('public.nil_google_place_idx') is not null),
    ('Index: cuisines_created_by_idx', to_regclass('public.cuisines_created_by_idx') is not null),
    ('Index: thrones_crowned_at_idx', to_regclass('public.thrones_crowned_at_idx') is not null),
    ('Index: app_errors_last_seen_idx', to_regclass('public.app_errors_last_seen_idx') is not null),
    ('Index: content_removals_user_idx', to_regclass('public.content_removals_user_idx') is not null),
    ('Access rule: "lookup cache readable" on place_lookup_cache', exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'place_lookup_cache' and policyname = 'lookup cache readable')),
    ('Access rule: "restaurants readable" on restaurants', exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'restaurants' and policyname = 'restaurants readable')),
    ('Access rule: "feedback insert own" on feedback', exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'feedback' and policyname = 'feedback insert own')),
    ('Access rule: "feedback read own or owner" on feedback', exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'feedback' and policyname = 'feedback read own or owner')),
    ('Access rule: "review photos readable" on storage.objects', exists (select 1 from pg_policies where schemaname = 'storage' and tablename = 'objects' and policyname = 'review photos readable')),
    ('Access rule: "review photos insertable by owner" on storage.objects', exists (select 1 from pg_policies where schemaname = 'storage' and tablename = 'objects' and policyname = 'review photos insertable by owner')),
    ('Access rule: "review photos deletable by owner" on storage.objects', exists (select 1 from pg_policies where schemaname = 'storage' and tablename = 'objects' and policyname = 'review photos deletable by owner')),
    ('Access rule: "avatars readable" on storage.objects', exists (select 1 from pg_policies where schemaname = 'storage' and tablename = 'objects' and policyname = 'avatars readable')),
    ('Access rule: "avatars insertable by owner" on storage.objects', exists (select 1 from pg_policies where schemaname = 'storage' and tablename = 'objects' and policyname = 'avatars insertable by owner')),
    ('Access rule: "avatars updatable by owner" on storage.objects', exists (select 1 from pg_policies where schemaname = 'storage' and tablename = 'objects' and policyname = 'avatars updatable by owner')),
    ('Access rule: "avatars deletable by owner" on storage.objects', exists (select 1 from pg_policies where schemaname = 'storage' and tablename = 'objects' and policyname = 'avatars deletable by owner')),
    ('Access rule: "profiles readable" on profiles', exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'profiles' and policyname = 'profiles readable')),
    ('Access rule: "own profile writable" on profiles', exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'profiles' and policyname = 'own profile writable')),
    ('Access rule: "cuisines readable" on cuisines', exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'cuisines' and policyname = 'cuisines readable')),
    ('Access rule: "cuisines insertable" on cuisines', exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'cuisines' and policyname = 'cuisines insertable')),
    ('Access rule: "thrones readable" on thrones', exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'thrones' and policyname = 'thrones readable')),
    ('Access rule: "own thrones writable" on thrones', exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'thrones' and policyname = 'own thrones writable')),
    ('Access rule: "fallen readable" on fallen', exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'fallen' and policyname = 'fallen readable')),
    ('Access rule: "own list only" on next_in_line', exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'next_in_line' and policyname = 'own list only')),
    ('Access rule: "followers see visited picks" on next_in_line', exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'next_in_line' and policyname = 'followers see visited picks')),
    ('Access rule: "rank promotions readable" on rank_promotions', exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'rank_promotions' and policyname = 'rank promotions readable')),
    ('Access rule: "own rank promotions insertable" on rank_promotions', exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'rank_promotions' and policyname = 'own rank promotions insertable')),
    ('Access rule: "own dismissed notifications" on dismissed_notifications', exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'dismissed_notifications' and policyname = 'own dismissed notifications')),
    ('Access rule: "endorsements readable" on endorsements', exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'endorsements' and policyname = 'endorsements readable')),
    ('Access rule: "own endorsements writable" on endorsements', exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'endorsements' and policyname = 'own endorsements writable')),
    ('Access rule: "follows readable" on follows', exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'follows' and policyname = 'follows readable')),
    ('Access rule: "own follows writable" on follows', exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'follows' and policyname = 'own follows writable')),
    ('Access rule: "remove an incoming follow you''ve blocked" on follows', exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'follows' and policyname = 'remove an incoming follow you''ve blocked')),
    ('Access rule: "no follows across a block" on follows', exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'follows' and policyname = 'no follows across a block')),
    ('Access rule: "own blocks readable" on blocks', exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'blocks' and policyname = 'own blocks readable')),
    ('Access rule: "own blocks writable" on blocks', exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'blocks' and policyname = 'own blocks writable')),
    ('Access rule: "users log their own ai calls" on ai_calls', exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'ai_calls' and policyname = 'users log their own ai calls')),
    ('Access rule: "users read their own ai calls" on ai_calls', exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'ai_calls' and policyname = 'users read their own ai calls')),
    ('Access rule: "conquests readable" on conquests', exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'conquests' and policyname = 'conquests readable')),
    ('Access rule: "own conquests writable" on conquests', exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'conquests' and policyname = 'own conquests writable')),
    ('Access rule: "thrones coup rate limit" on thrones', exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'thrones' and policyname = 'thrones coup rate limit')),
    ('Access rule: "next in line insert rate limit" on next_in_line', exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'next_in_line' and policyname = 'next in line insert rate limit')),
    ('Access rule: "review photos insert rate limit" on storage.objects', exists (select 1 from pg_policies where schemaname = 'storage' and tablename = 'objects' and policyname = 'review photos insert rate limit')),
    ('Access rule: "owner reads signup sources" on signup_sources', exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'signup_sources' and policyname = 'owner reads signup sources')),
    ('Access rule: "invites readable by the two people and the owner" on invites', exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'invites' and policyname = 'invites readable by the two people and the owner')),
    ('Access rule: "owner reads place refresh issues" on place_refresh_issues', exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'place_refresh_issues' and policyname = 'owner reads place refresh issues')),
    ('Access rule: "closed places readable" on closed_places', exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'closed_places' and policyname = 'closed places readable')),
    ('Access rule: "cuisines icon updatable by creator" on cuisines', exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'cuisines' and policyname = 'cuisines icon updatable by creator')),
    ('Access rule: "place pages readable" on place_pages', exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'place_pages' and policyname = 'place pages readable')),
    ('Access rule: "owner reads errors" on app_errors', exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'app_errors' and policyname = 'owner reads errors')),
    ('Access rule: "owner clears errors" on app_errors', exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'app_errors' and policyname = 'owner clears errors')),
    ('Access rule: "author and owner read removals" on content_removals', exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'content_removals' and policyname = 'author and owner read removals')),
    ('Access rule: "feedback insert rate limit" on feedback', exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'feedback' and policyname = 'feedback insert rate limit')),
    ('Old access rule removed: "signed-in users populate the cache" on place_lookup_cache', not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'place_lookup_cache' and policyname = 'signed-in users populate the cache')),
    ('Old access rule removed: "signed-in users refresh the cache" on place_lookup_cache', not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'place_lookup_cache' and policyname = 'signed-in users refresh the cache')),
    ('Old access rule removed: "own fallen writable" on fallen', not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'fallen' and policyname = 'own fallen writable')),
    ('Privacy: profile settings are hidden from other people', case when exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'profiles' and column_name = 'a11y_prefs') then not has_column_privilege('anon', 'public.profiles', 'a11y_prefs', 'SELECT') else false end),
    ('Uploads: photo buckets limited to images up to 5 MB', (select count(*) from storage.buckets where id in ('avatars', 'review-photos') and file_size_limit = 5242880) = 2)
)
select 'Missing or out of date: ' || item as result from checks where not ok
union all
select 'All good - your database matches the latest schema.sql (' || (select count(*) from checks) || ' checks passed)'
where not exists (select 1 from checks where not ok);
